<?php
/**
 * Models from schema: market version 0.1
 * Code generated by TransformTask
 *
 */

/**
 * @todo: Copy this file to app/lang/<lang>/category.php
 * Modify the values accordingly
 */
return array(
	'_name' => 'Category',
    '_name_plural' => 'Categories',
    'parent_sid' => 'Parent Sid',
    'type' => 'Type',
    'name' => 'Name',
    'code' => 'Code',
    'description' => 'Description',
    'image_uri' => 'Image Uri',
    'position' => 'Position',
    'params_text' => 'Params Text',
);
