<?php
/**
 * Models from schema: market version 0.1
 * Code generated by TransformTask
 *
 */

/**
 * @todo: Copy this file to app/lang/<lang>/code_ref.php
 * Modify the values accordingly
 */
return array(
	'_name' => 'Code',
    '_name_plural' => 'Codes',
    'parent_sid' => 'Parent Sid',
    'kind' => 'Kind',
    'name' => 'Name',
    'code' => 'Code',
    'abbreviation' => 'Abbreviation',
    'description' => 'Description',
    'position' => 'Position',
    'params_text' => 'Params Text',
);
