<?php
/**
 * Models from schema: market version 0.1
 * Code generated by TransformTask
 *
 */

/**
 * @todo: Copy this file to app/lang/<lang>/organization.php
 * Modify the values accordingly
 */
return array(
    '_name' => 'Organization',
    '_name_plural' => 'Organizations',
    'parent_sid' => 'Parent Sid',
    'id' => 'ID',
    'name' => 'Name',
    'name_nl' => 'Name Lc',
    'category' => 'Category',
    'role' => 'Role',
    'registration_num' => 'Registration Num',
    'inet_domain_name' => 'Inet Domain Name',
    'url' => 'Url',
    'country_cd' => 'Country',
    'province_cd' => 'Province',
    'district' => 'District',
    'address' => 'Address',
    'postal_code' => 'Postal Code',
    'catchphrase' => 'Catchphrase',
    'summary' => 'Summary',
    'description' => 'Description',
    'logo_img_uri' => 'Logo Img Uri',
    'cover_img_uri' => 'Cover Img Uri',
    'found_date' => 'Found Date',
    'transaction' => 'Transaction',
    'num_members' => 'Num Members',
    'num_comments' => 'Num Comments',
    'num_cheers' => 'Num Cheers',
    'params_text' => 'Params Text',
);
