<?php
/**
 * Models from schema: docuflow version 0.1
 * Code generated by TransformTask
 *
 */

/**
 * @todo: Copy this file to app/lang/<lang>/role.php
 * Modify the values accordingly
 */
return array(
    '_name' => 'Role',
    '_name_plural' => 'Roles',
    'subject_type' => 'Subject Type',
    'name' => 'Name',
    'params_text' => 'Params Text',
);
