<?php namespace Altenia\Ecofy\Module\Task;
/**
 * Models from schema: AldosEngine version 0.1
 * Code generated by TransformTask
 *
 */

use Altenia\Ecofy\Controller\GenericServiceController;
use Altenia\Ecofy\Service\ServiceRegistry;

/**
 * Controller class that provides REST API to Task resource
 */
class TaskController extends GenericServiceController {

	public function __construct() {
		parent::__construct('layouts.workspace', 'svc:task', 'Task');
	}

	public function indexAuxData() {
		$auxdata = array();

		$auxdata['opt_status'] = array(
				'0' => \Lang::get('task.status_defined'), 
				'1' => \Lang::get('task.status_allocated'), 
				'2' => \Lang::get('task.status_completed')
			);
		$auxdata['opt_record_status'] = array(
				'0' => \Lang::get('task.record_status_accessible'), 
				'1' => \Lang::get('task.record_status_deleted'), 
				'2' => \Lang::get('task.record_status_archived')
			);

		// Sets the end of the timeframe period
		$thisWeek = strtotime( "next monday" );
		$nextWeek = strtotime( "next monday + 7 days" );
		$thisMonth = date("Y-m-t");
		$nextMonth = strtotime( "next friday" );
		$thisYear = strtotime( "previous friday" );
		$thisYear = strtotime( "previous friday" );
		$auxdata['opt_timeframe'] = array(
				'0' => \Lang::get('task.this_week'), 
				'1' => \Lang::get('task.next_week'), 
				'2' => \Lang::get('task.this_month'),
				'2' => \Lang::get('task.next_month'),
				'2' => \Lang::get('task.this_year'),
				'2' => \Lang::get('task.next_year')
			);

		return $auxdata;
	}

	public function createAuxData() {
		$auxdata = $this->indexAuxData();
		
		return $auxdata;
	}
	
	public function editAuxData(&$record) {
		$auxdata = $this->indexAuxData();
		
		return $auxdata;
	}

	
}