<?php namespace Altenia\Ecofy\Module\Task;
/**
 * Models from schema: AldosEngine version 0.1
 * Code generated by TransformTask
 *
 */

use Altenia\Ecofy\Controller\GenericNestedServiceController;
use Altenia\Ecofy\Service\ServiceRegistry;

/**
 * Controller class that provides REST API to Task resource
 */
class TaskLogEntryController extends GenericNestedServiceController {

	public function __construct() {
		parent::__construct('layouts.workspace', 'svc:task_log_entry', 'task_sid', 'TaskLogEntry', 'TaskLogEntries');
	}

	public function indexAuxData() {
		$auxdata = array();

		$auxdata['opt_status'] = array(
				'0' => \Lang::get('task.status_notcarriedout'), 
				'1' => \Lang::get('task.status_carriedout')
			);
		$auxdata['opt_status_reason'] = array(
				'deprioritized' => \Lang::get('task.status_reason_deprioritized'), 
				'notneeded' => \Lang::get('task.status_reason_notneeded'), 
				'notime' => \Lang::get('task.status_reason_notime')
			);

		return $auxdata;
	}

	public function createAuxData() {
		$auxdata = $this->indexAuxData();
		
		return $auxdata;
	}
	
	public function editAuxData(&$record) {
		$auxdata = $this->indexAuxData();
		
		return $auxdata;
	}

	
}