<?php namespace Altenia\Ecofy\Module\CodeRef;
/**
 * Models from schema: AldosEngine version 0.1
 * Code generated by TransformTask
 *
 */

use Altenia\Ecofy\Controller\GenericServiceController;

/**
 * Controller class that provides REST API to User resource
 */
class CodeRefController extends GenericServiceController {

	public function __construct() {
		parent::__construct('layouts.workspace', 'svc:code_ref', 'CodeRef');
	}


	public function showAuxData(&$record) {
		$auxdata = array();
		return $auxdata;
	}
}