<?php namespace Altenia\Ecofy\Module\Security;
/**
 * Models from schema: AldosEngine version 0.1
 * Code generated by TransformTask
 *
 */


/**
 * Controller class that provides REST API to User resource
 */
class AccessControlApiController extends \GenericServiceApiController {

	public function __construct() {
		parent::__construct('svc:access_control', 'AccessControl');
	}

	/**
	 * Store a newly created resource in storage.
	 *
	 * @return Response
	 */
	public function store()
	{
		$data = Input::all();

		$createMethod = 'create' . $this->modelName;
		$updateMethod = 'update' . $this->modelName;

		$query = array('role_sid' => $data['role_sid'], 
			'service' => $data['service']);
		$record = $this->service->findAccessControl($query);

        try {
			if ($record) {
				// If entry found: Merge policies
				//$data['permissions'] = $record->permissions;
				$record->updatePolicy($data['resource'], $data['resource_permissions']);
				$data['policy'] = $record->policy;

	            $record = $this->service->$updateMethod($record->sid, $data);
			} else {
	            $record = $this->service->$createMethod($data);
			}

            return Response::json(array(
                'sid' => $record->sid),
                201
            );
        } catch (Exception $e) {
            return Response::json(array(
                'error' => $e->getMessage()),
                400
            );
        }
	}
}