<?php
/**
 * Models from schema: ecofy version 0.1
 * Code generated by TransformTask
 *
 */

/**
 * Copy this file to app/database/seeds directory.
 * Add the line $this->call('UserTableSeeder');
 * into the DatabaseSeeder.php's run() method.
 * To run the migration script do: $php artisan db:seed
 */
class UsersTableSeeder extends Seeder {

	/**
	 * Run the migrations.
	 *
	 * @return void
	 */
	public function run()
	{
	    $users = array(
            array(
			'uuid' => '-admin-',
			'domain_sid' => 1,
			'domain_id' => 'domain_id',
			'created_by' => 1,
			'updated_by' => 1,
			'lang' => 'en',
			'organization_sid' => 'host',
			'role_sid' => 1,
			'role_name' => 'admin',
			'id' => 'admin',
			'password' => 'admin',
			'given_name' => 'Admin',
			'middle_name' => '',
			'family_name' => 'Host',
			'name_nl' => 'admin',
			'name' => 'admin',
			//'dob' => '',
			'phone' => 'na',
			'email' => 'admin@here.com',
			'timezone' => '',
			'type' => 'admin',
			'permalink' => '',
			'profile_image_url' => '',
			'activation_code' => 'admincode',
			'security_question' => 'who are you',
			'security_answer' => 'admin',
			//'session_timestamp' => '',
			'last_session_ip' => 'localhost',
			'last_session_dt' => new DateTime,
			'login_fail_counter' => 0,
			'active' => true,
			'status' => 1,
			'default_lang_cd' => 'en',
			'expiry_dt' => new DateTime,
			'params_text' => '',
            )
        );
	    $userService = new Altenia\Ecofy\Module\User\UserService(
	    		new Altenia\Ecofy\Module\User\UserDaoEloquent()
	    	);
        foreach ($users as $user) {
            $userService->createUser($user);
        }

	}
}
