<?php namespace Altenia\Ecofy\Module\Role;
/**
 * Models from schema: AldosEngine version 0.1
 * Code generated by TransformTask
 *
 */

use Altenia\Ecofy\Controller\GenericServiceController;

/**
 * Controller class that provides REST API to User resource
 */
class RoleController extends GenericServiceController {

	public function __construct() {
		parent::__construct('layouts.workspace', 'svc:role', 'Role');
	}


	public function showAuxData(&$record) {
		$auxdata = array();
		$opt_permissions[1] = 'read';
		$opt_permissions[2] = 'update';
		$opt_permissions[4] = 'create';
		$opt_permissions[8] = 'delete';
		$opt_permissions[16] = 'admin';
		/*
		$opt_permissions[32] = 'g read';
		$opt_permissions[64] = 'g update';
		$opt_permissions[128] = 'g create';
		$opt_permissions[256] = 'g delete';
		$opt_permissions[512] = 'g admin';
		$opt_permissions[1024] = 'g read';
		*/
		$auxdata['opt_permissions'] = $opt_permissions;

		return $auxdata;
	}
}