<?php namespace Altenia\Ecofy\Module\Category;
/**
 * Models from schema: AldosEngine version 0.1
 * Code generated by TransformTask
 *
 */

use Altenia\Ecofy\Controller\GenericServiceController;

/**
 * Controller class that provides REST API to User resource
 */
class CategoryController extends GenericServiceController {

	public function __construct() {
		parent::__construct('layouts.workspace', 'svc:category', 'Category', 'Categories');
	}


	public function showAuxData(&$record) {
		$auxdata = array();
		return $auxdata;
	}
}